BOT_TOKEN         = "YOUR_BOT_TOKEN"
MONGO_URI         = "YOUR_MONGODB_URI"
WELCOME_IMAGE_URL = "https://files.catbox.moe/g2rsjz.jpg"
SUPPORT_URL       = "https://t.me/CarelessxWorld"
UPDATE_URL        = "https://t.me/ll_CarelessxCoder_ll"
OWNER_URL         = "https://t.me/CarelessxOwner"
